# Generated by Django 4.1.12 on 2024-03-11 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1000)),
                ("isCorrect", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Options",
        ),
    ]
