# Generated by Django 4.1.12 on 2024-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0003_questionoption_delete_questionoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="point",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="question",
            field=models.CharField(default="Test Default Question", max_length=255),
        ),
    ]
