# Generated by Django 4.1.12 on 2024-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0004_questionbank_image_questionbank_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionbank",
            name="level",
        ),
    ]
