# Generated by Django 4.1.12 on 2024-03-11 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0005_remove_questionbank_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question_bank_api.questionbank",
            ),
        ),
        migrations.CreateModel(
            name="QuestionLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.CharField(max_length=10)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_bank_api.questionbank",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
