# Generated by Django 4.1.12 on 2024-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0006_alter_questionoption_question_questionlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
