# Generated by Django 4.1.12 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0007_alter_questionbank_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
