# Generated by Django 4.1.12 on 2024-03-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank_api", "0008_alter_questionbank_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionbank",
            name="point",
        ),
        migrations.RemoveField(
            model_name="questionlevel",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="name",
        ),
        migrations.AddField(
            model_name="questionbank",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="question_bank_api.questionlevel",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="option",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="question",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="questionlevel",
            name="level",
            field=models.CharField(
                choices=[("1", "Level 1"), ("2", "Level 2"), ("3", "Level 3")],
                max_length=1,
            ),
        ),
    ]
